# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

kos:
  - build: main
    repository: ghcr.io/dwsr/krmfn-sealedsecret-from-1password/krmfn
    platforms:
      - linux/arm64
      - linux/amd64
    labels: 
        org.opencontainers.image.created: "{{.Date}}"
        org.opencontainers.image.name: "{{.ProjectName}}"
        org.opencontainers.image.revision: "{{.FullCommit}}"
        org.opencontainers.image.version: "{{.Version}}"
        org.opencontainers.image.source: "{{.GitURL}}"
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - "{{.ShortCommit}}"
    sbom: spdx
    bare: true

gomod:
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

builds:
  - id: main
    main: ./cmd/krmfn
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
